#!/usr/bin/env node
/**
 * One-command local development.
 *
 *   npm run dev
 *
 * Takes a fresh clone to a running API + playground with no other steps, and is
 * idempotent, so it is equally the first-run command and the everyday one.
 *
 * It picks one of two modes depending on what the machine has:
 *
 *   Docker present  PostgreSQL in a container, code executed in throwaway
 *                   containers. Sandboxed. This is the recommended mode.
 *   No Docker       SQLite file, code executed as child processes of the API.
 *                   NO SANDBOX — see the warning printed at startup.
 *
 * Deliberately dependency-free: adding `concurrently` to run two processes
 * would mean an npm install before the script that performs the npm install.
 */
import { spawn, spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const isWindows = process.platform === 'win32';

const colour = process.stdout.isTTY && !process.env.NO_COLOR;
const ESC = String.fromCharCode(27); // ANSI escape, kept out of the source as a literal
const paint = (code, text) => (colour ? `${ESC}[${code}m${text}${ESC}[0m` : text);
const step = (msg) => console.log(`${paint('36;1', '▸')} ${paint('1', msg)}`);
const info = (msg) => console.log(`  ${paint('90', msg)}`);
const warn = (msg) => console.log(`${paint('33;1', '!')} ${msg}`);

function die(msg, hint) {
  console.error(`\n${paint('31;1', '✗')} ${msg}`);
  if (hint) console.error(`\n${hint}\n`);
  process.exit(1);
}

/**
 * On Windows `npm` and `npx` are .cmd shims, which Node refuses to spawn
 * without a shell. Passing an args ARRAY alongside `shell: true` is deprecated
 * (DEP0190) because the arguments are concatenated rather than escaped, so the
 * command is pre-joined into a single string instead. Every argument used here
 * is a literal flag or a relative path with no spaces.
 */
const needsShell = (command) => isWindows && (command === 'npm' || command === 'npx');
const asShellCommand = (command, args) => [command, ...args].join(' ');

/** Runs a command to completion. Returns its exit code and captured output. */
function run(command, args, options = {}) {
  const shell = needsShell(command);
  const result = spawnSync(shell ? asShellCommand(command, args) : command, shell ? [] : args, {
    cwd: root,
    stdio: options.quiet ? 'pipe' : 'inherit',
    shell,
    encoding: 'utf8',
    ...options,
  });
  return { code: result.status ?? 1, out: `${result.stdout ?? ''}${result.stderr ?? ''}` };
}

/** True when a working `<tool> --version` exists on PATH. */
function toolPresent(tool) {
  return spawnSync(tool, ['--version'], { stdio: 'ignore', timeout: 5_000 }).status === 0;
}

// --- mode selection ----------------------------------------------------------

step('Checking what this machine has');

// `docker version` talks to the daemon; `docker --version` only reports the
// client and succeeds even when nothing is running.
const hasDocker =
  run('docker', ['version', '--format', '{{.Server.Version}}'], { quiet: true }).code === 0;

const mode = hasDocker ? 'docker' : 'native';

if (hasDocker) {
  info('Docker is running — using PostgreSQL and the sandboxed Docker executor');
} else {
  info('No Docker daemon — using SQLite and the native executor (no sandbox)');
}

// --- environment -------------------------------------------------------------

const envPath = path.join(root, '.env');

if (existsSync(envPath)) {
  step('Environment already configured');
  info('.env present — leaving it alone');
} else if (mode === 'docker') {
  step('Generating .env files with fresh secrets (first run only)');

  // Prefer PowerShell 7 (`pwsh`) when it is installed, but fall back to the
  // Windows PowerShell 5.1 that ships with the OS — setup.ps1 supports both.
  const powershell = isWindows && toolPresent('pwsh') ? 'pwsh' : 'powershell';

  const setup = isWindows
    ? run(powershell, ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', 'setup.ps1'])
    : run('bash', ['setup.sh']);

  if (setup.code !== 0) die('setup failed — see the output above.');
} else {
  // setup.sh/setup.ps1 both require a reachable Docker daemon (they render
  // compose config and pre-pull runner images), so native mode writes its own
  // much smaller env instead of trying to reuse them.
  step('Generating .env for zero-setup mode (first run only)');

  writeFileSync(
    envPath,
    [
      '# Generated by `npm run dev` on a machine without Docker.',
      '#',
      '# SQLite means no database server to install; EXECUTOR=native means code',
      '# runs as a child process of the API, with NO SANDBOX. Install Docker and',
      '# delete this file to switch to the isolated backend.',
      'NODE_ENV=development',
      'PORT=4000',
      '# Loopback only. The API refuses to start on a public interface while',
      '# EXECUTOR=native, because that would be remote code execution as you.',
      'HOST=127.0.0.1',
      '',
      '# Relative to prisma/, where the schema lives.',
      'DATABASE_URL="file:./dev.db"',
      `JWT_SECRET=${randomBytes(48).toString('hex')}`,
      'EXECUTOR=native',
      'CORS_ORIGIN=*',
      '',
    ].join('\n'),
    'utf8',
  );
  info('Wrote .env (SQLite + native executor)');
}

// --- database ----------------------------------------------------------------

// Prisma cannot take `provider` from an env var, so the SQLite build is a copy
// of the canonical schema with only the datasource swapped. Regenerated every
// run, so it cannot drift from prisma/schema.prisma.
const SQLITE_SCHEMA = path.join(root, 'prisma', 'schema.sqlite.prisma');

function writeSqliteSchema() {
  const canonical = readFileSync(path.join(root, 'prisma', 'schema.prisma'), 'utf8');
  const swapped = canonical.replace(/provider\s*=\s*"postgresql"/, 'provider = "sqlite"');

  if (swapped === canonical) {
    die('Could not derive the SQLite schema — the datasource block in prisma/schema.prisma changed.');
  }

  writeFileSync(
    SQLITE_SCHEMA,
    `// GENERATED by scripts/dev.mjs from schema.prisma — do not edit.\n${swapped}`,
    'utf8',
  );
}

if (mode === 'docker') {
  step('Starting PostgreSQL');
  // --wait blocks until the healthcheck passes, so migrations below cannot race
  // a database that is still starting up.
  if (run('docker', ['compose', 'up', '-d', '--wait', 'postgres']).code !== 0) {
    die(
      'Could not start the postgres container.',
      'If the port is already taken, change POSTGRES_PORT in .env and .env.docker.',
    );
  }
  info('PostgreSQL is healthy');
}

step('Preparing the database');

const schemaArgs = mode === 'native' ? ['--schema', SQLITE_SCHEMA] : [];
if (mode === 'native') writeSqliteSchema();

const generate = run('npx', ['prisma', 'generate', ...schemaArgs], { quiet: true });
if (generate.code !== 0) {
  console.error(generate.out);
  die(
    '`prisma generate` failed.',
    'On Windows this is usually a file lock: another `npm run dev` (or a stray\n' +
      'tsx/next process from one) still holds the Prisma query engine. Close it,\n' +
      'or kill leftover node processes, then try again.',
  );
}
info('Prisma client generated');

// Postgres gets the checked-in migrations. SQLite gets `db push`: the migration
// history is Postgres-specific SQL, and a local scratch database does not need
// a history — the schema is the only thing that matters.
const applied =
  mode === 'docker'
    ? run('npx', ['prisma', 'migrate', 'deploy'], { quiet: true })
    : run('npx', ['prisma', 'db', 'push', '--skip-generate', ...schemaArgs], { quiet: true });

if (applied.code !== 0) {
  console.error(applied.out);

  // Postgres only runs its initialisation — the step that creates the user and
  // sets the password — on an EMPTY data directory. A volume left over from a
  // different checkout, or from before the secrets were regenerated, keeps its
  // original password forever, so a correct .env still cannot log in. Prisma
  // reports this as a bare P1000 with no hint that the volume is the cause.
  const staleVolume = /\bP1000\b|authentication failed/i.test(applied.out);

  die(
    mode === 'docker' ? '`prisma migrate deploy` failed.' : '`prisma db push` failed.',
    staleVolume
      ? 'The password in .env does not match the one baked into the existing\n' +
          'PostgreSQL volume. Postgres sets the password only when it initialises an\n' +
          'empty data directory, so a volume from an older checkout keeps the old one.\n\n' +
          'Discard it (this deletes local execution history, nothing else):\n\n' +
          '    docker compose down -v && npm run dev'
      : undefined,
  );
}
info(mode === 'docker' ? 'Migrations applied' : 'SQLite schema synced');

// The seed upserts two accounts, so re-running it is harmless.
const seed = run('npx', ['prisma', 'db', 'seed', ...schemaArgs], { quiet: true });
if (seed.code === 0) info('Seed accounts ready');
else warn('Seeding failed — the app will still run, but the demo logins may be missing.');

// --- web dependencies --------------------------------------------------------

if (existsSync(path.join(root, 'web', 'node_modules'))) {
  step('Playground dependencies already installed');
} else {
  step('Installing playground dependencies (first run only — this takes a minute)');
  if (run('npm', ['install'], { cwd: path.join(root, 'web') }).code !== 0) {
    die('Installing the web dependencies failed.');
  }
}

// --- run both ----------------------------------------------------------------

if (mode === 'native') {
  // Report the language set up front. Without this the first failed run looks
  // like an engine bug rather than a missing compiler.
  const toolchains = [
    ['Python', ['python3', 'python']],
    ['Node.js', ['node']],
    ['C / C++', ['gcc', 'g++']],
    ['Bash', ['bash']],
  ];

  step('Languages available natively');
  for (const [label, candidates] of toolchains) {
    const found = candidates.find(toolPresent);
    info(found ? `${label}: ${found}` : `${label}: not installed — runs will report this`);
  }

  console.log(`
${paint('33;1', '  ⚠  NO SANDBOX')}

  Docker was not found, so submitted code runs as a child of the API with your
  files, network and privileges. That is fine while you are the only one
  writing the code — it is not safe to expose. The API is bound to 127.0.0.1
  and will refuse to start on a public interface in this mode.

  Install Docker and re-run for the isolated backend.`);
}

console.log(`
${paint('32;1', '✓ Ready')}

  ${paint('1', 'Playground')}  ${paint('4', 'http://localhost:3000/playground')}
  ${paint('1', 'API')}         ${paint('4', 'http://localhost:4000')}

  Sign in with either seeded account:
    coder@example.com / Password123!
    admin@example.com / Admin123!

  Press ${paint('1', 'Ctrl+C')} to stop both.
`);

const children = [];

function start(label, colourCode, command, args, cwd) {
  const shell = needsShell(command);
  const child = spawn(shell ? asShellCommand(command, args) : command, shell ? [] : args, {
    cwd,
    shell,
    env: process.env,
  });
  const tag = paint(colourCode, `[${label}]`);

  // Line-buffer so a prefix is never stamped mid-line.
  const pipe = (stream) => {
    let buffer = '';
    stream.on('data', (chunk) => {
      buffer += chunk.toString();
      const lines = buffer.split('\n');
      buffer = lines.pop() ?? '';
      for (const line of lines) console.log(`${tag} ${line}`);
    });
  };

  pipe(child.stdout);
  pipe(child.stderr);

  child.on('exit', (code, signal) => {
    if (!shuttingDown) {
      warn(`${label} exited (${signal ?? code}) — shutting the other process down too.`);
      shutdown();
    }
  });

  children.push(child);
  return child;
}

let shuttingDown = false;
function shutdown() {
  if (shuttingDown) return;
  shuttingDown = true;
  for (const child of children) {
    if (!child.killed) child.kill('SIGINT');
  }
  // Don't leave the terminal hanging if something ignores SIGINT.
  setTimeout(() => process.exit(0), 4000).unref();
}

process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);

start('api', '36', 'npx', ['tsx', 'watch', 'src/server.ts'], root);
start('web', '35', 'npm', ['run', 'dev'], path.join(root, 'web'));
